apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: kube-system
  name: downscaler
  labels:
    k8s-app: downscaler
spec:
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        k8s-app: downscaler
    spec:
      # run on each master node
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists
      hostNetwork: true
      containers:
      - name: downscaler
        image: x0rg/kube-nodes-downscaler:v0.0.3
        imagePullPolicy: Always
        args:
          - --start=7
          - --end=17
          - --asg-name=FOO
          - --interval=30s
        resources:
          requests:
            memory: 20Mi
            cpu: 10m
          limits:
            memory: 20Mi
            cpu: 100m
